// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repository

import (
	"github.com/google/uuid"
	"github.com/kuchida1981/friii/internal/domain/entity"
	"sync"
	"time"
)

// Ensure, that JournalRepositoryMock does implement JournalRepository.
// If this is not the case, regenerate this file with moq.
var _ JournalRepository = &JournalRepositoryMock{}

// JournalRepositoryMock is a mock implementation of JournalRepository.
//
//	func TestSomethingThatUsesJournalRepository(t *testing.T) {
//
//		// make and configure a mocked JournalRepository
//		mockedJournalRepository := &JournalRepositoryMock{
//			FindByIDFunc: func(id uuid.UUID) (*entity.JournalEntry, error) {
//				panic("mock out the FindByID method")
//			},
//			ListFunc: func(from time.Time, to time.Time) ([]*entity.JournalEntry, error) {
//				panic("mock out the List method")
//			},
//			SaveFunc: func(entry *entity.JournalEntry) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedJournalRepository in code that requires JournalRepository
//		// and then make assertions.
//
//	}
type JournalRepositoryMock struct {
	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(id uuid.UUID) (*entity.JournalEntry, error)

	// ListFunc mocks the List method.
	ListFunc func(from time.Time, to time.Time) ([]*entity.JournalEntry, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(entry *entity.JournalEntry) error

	// calls tracks calls to the methods.
	calls struct {
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// ID is the id argument value.
			ID uuid.UUID
		}
		// List holds details about calls to the List method.
		List []struct {
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Entry is the entry argument value.
			Entry *entity.JournalEntry
		}
	}
	lockFindByID sync.RWMutex
	lockList     sync.RWMutex
	lockSave     sync.RWMutex
}

// FindByID calls FindByIDFunc.
func (mock *JournalRepositoryMock) FindByID(id uuid.UUID) (*entity.JournalEntry, error) {
	if mock.FindByIDFunc == nil {
		panic("JournalRepositoryMock.FindByIDFunc: method is nil but JournalRepository.FindByID was just called")
	}
	callInfo := struct {
		ID uuid.UUID
	}{
		ID: id,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(id)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedJournalRepository.FindByIDCalls())
func (mock *JournalRepositoryMock) FindByIDCalls() []struct {
	ID uuid.UUID
} {
	var calls []struct {
		ID uuid.UUID
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *JournalRepositoryMock) List(from time.Time, to time.Time) ([]*entity.JournalEntry, error) {
	if mock.ListFunc == nil {
		panic("JournalRepositoryMock.ListFunc: method is nil but JournalRepository.List was just called")
	}
	callInfo := struct {
		From time.Time
		To   time.Time
	}{
		From: from,
		To:   to,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(from, to)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedJournalRepository.ListCalls())
func (mock *JournalRepositoryMock) ListCalls() []struct {
	From time.Time
	To   time.Time
} {
	var calls []struct {
		From time.Time
		To   time.Time
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *JournalRepositoryMock) Save(entry *entity.JournalEntry) error {
	if mock.SaveFunc == nil {
		panic("JournalRepositoryMock.SaveFunc: method is nil but JournalRepository.Save was just called")
	}
	callInfo := struct {
		Entry *entity.JournalEntry
	}{
		Entry: entry,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(entry)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedJournalRepository.SaveCalls())
func (mock *JournalRepositoryMock) SaveCalls() []struct {
	Entry *entity.JournalEntry
} {
	var calls []struct {
		Entry *entity.JournalEntry
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
