// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repository

import (
	"github.com/kuchida1981/friii/internal/domain/entity"
	"sync"
)

// Ensure, that JournalRepositoryMock does implement JournalRepository.
// If this is not the case, regenerate this file with moq.
var _ JournalRepository = &JournalRepositoryMock{}

// JournalRepositoryMock is a mock implementation of JournalRepository.
//
//	func TestSomethingThatUsesJournalRepository(t *testing.T) {
//
//		// make and configure a mocked JournalRepository
//		mockedJournalRepository := &JournalRepositoryMock{
//			FindAllFunc: func() ([]*entity.JournalEntry, error) {
//				panic("mock out the FindAll method")
//			},
//			SaveFunc: func(entry *entity.JournalEntry) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedJournalRepository in code that requires JournalRepository
//		// and then make assertions.
//
//	}
type JournalRepositoryMock struct {
	// FindAllFunc mocks the FindAll method.
	FindAllFunc func() ([]*entity.JournalEntry, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(entry *entity.JournalEntry) error

	// calls tracks calls to the methods.
	calls struct {
		// FindAll holds details about calls to the FindAll method.
		FindAll []struct {
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Entry is the entry argument value.
			Entry *entity.JournalEntry
		}
	}
	lockFindAll sync.RWMutex
	lockSave    sync.RWMutex
}

// FindAll calls FindAllFunc.
func (mock *JournalRepositoryMock) FindAll() ([]*entity.JournalEntry, error) {
	if mock.FindAllFunc == nil {
		panic("JournalRepositoryMock.FindAllFunc: method is nil but JournalRepository.FindAll was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFindAll.Lock()
	mock.calls.FindAll = append(mock.calls.FindAll, callInfo)
	mock.lockFindAll.Unlock()
	return mock.FindAllFunc()
}

// FindAllCalls gets all the calls that were made to FindAll.
// Check the length with:
//
//	len(mockedJournalRepository.FindAllCalls())
func (mock *JournalRepositoryMock) FindAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFindAll.RLock()
	calls = mock.calls.FindAll
	mock.lockFindAll.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *JournalRepositoryMock) Save(entry *entity.JournalEntry) error {
	if mock.SaveFunc == nil {
		panic("JournalRepositoryMock.SaveFunc: method is nil but JournalRepository.Save was just called")
	}
	callInfo := struct {
		Entry *entity.JournalEntry
	}{
		Entry: entry,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(entry)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedJournalRepository.SaveCalls())
func (mock *JournalRepositoryMock) SaveCalls() []struct {
	Entry *entity.JournalEntry
} {
	var calls []struct {
		Entry *entity.JournalEntry
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
